#if (!require("devtools")) install.packages("devtools")
# devtools::install_github("hadley/shinySignals")
# devtools::install_github("jcheng5/bubbles")
# devtools::install_github("Kohze/fireData")
library(shiny)
library(shinySignals)   
library(dplyr)
library(shinydashboard)
library(bubbles)        
library(fireData)
library(jsonlite)
library(httr)
# source("bloomfilter.R")